# Generated by Django 3.2.5 on 2021-10-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Notification_type',
            new_name='notification_type',
        ),
    ]
