# Generated by Django 3.2.5 on 2021-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
