# Generated by Django 3.2.5 on 2021-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210816_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='profile_pic',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
