# Generated by Django 3.2.5 on 2021-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210918_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='Landline',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='establishment_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='linkdin',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='registration_proof',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to='hospital/documents'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='specialist',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='website',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
    ]
