# Generated by Django 3.2.5 on 2021-09-25 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patients_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.TimeField(blank=True, max_length=500, null=True)),
                ('close_time', models.TimeField(blank=True, max_length=500, null=True)),
                ('break_start_time', models.TimeField(blank=True, max_length=500, null=True)),
                ('break_end_time', models.TimeField(blank=True, max_length=500, null=True)),
                ('monday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tuesday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('wednesday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('thursday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('friday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('saturday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('sunday', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
