# Generated by Django 3.2.5 on 2021-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210926_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
