# Generated by Django 3.2.5 on 2021-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patients_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
