# Generated by Django 3.2.5 on 2021-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210814_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalphones',
            old_name='email',
            new_name='hospital_email',
        ),
        migrations.RenameField(
            model_name='hospitalphones',
            old_name='mobile',
            new_name='hospital_mobile',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='Landline',
            new_name='alternate_mobile',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='linkdin',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='degree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='landline',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Hospital'), (3, 'Doctor'), (4, 'Patient'), (5, 'Lab'), (6, 'Pharmacy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='alternate_mobile',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='country',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='dob',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='fisrt_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='gender',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='state',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='zip_Code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='specialist',
            field=models.CharField(blank=True, choices=[(1, 'PHYSICIAN'), (2, 'SURGEN'), (3, 'CARDIOLOGY'), (4, 'NEUROLOGISTS')], default='', max_length=256, null=True),
        ),
    ]
