# Generated by Django 3.2.5 on 2021-09-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210918_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='linkdin',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='Landline',
            new_name='landline',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='desc',
        ),
        migrations.AddField(
            model_name='labs',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='linkedin',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='about',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='about',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
