# Generated by Django 3.2.5 on 2021-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patients_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='is_appiled',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_verified',
        ),
    ]
