# Generated by Django 3.2.5 on 2021-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210918_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
