# Generated by Django 3.2.5 on 2021-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210814_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_title',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
