# Generated by Django 3.2.5 on 2021-09-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_labs_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='contact_number',
            new_name='alternate_mobile',
        ),
    ]
