# Generated by Django 3.2.5 on 2021-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210818_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctors',
            name='ssn_id',
            field=models.IntegerField(default=1),
        ),
    ]
