# Generated by Django 3.2.5 on 2021-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_name_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminHOD'), (2, 'Hospitals'), (3, 'HospitalDoctors'), (4, 'Patients'), (5, 'Labs'), (6, 'Pharmacy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='establishment_year',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
