# Generated by Django 3.2.5 on 2021-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210930_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='firm',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
