# Generated by Django 3.2.5 on 2021-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitals_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
