# Generated by Django 3.2.5 on 2021-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitaldoctors_ssn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldoctors',
            name='admin',
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/Doctor/profile/images'),
        ),
    ]
