# Generated by Django 3.2.5 on 2021-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210814_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='establishment_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
