# Generated by Django 3.2.5 on 2021-09-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_contact_number_labs_alternate_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='Landline',
            new_name='alternate_mobile',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='contact_number',
            new_name='landline',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='registration_proof',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to='Pharmacist/documents'),
        ),
    ]
