# Generated by Django 3.2.5 on 2021-09-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210918_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='linkdin',
            new_name='linkedin',
        ),
    ]
