# Generated by Django 3.2.5 on 2021-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminHOD'), (2, 'Hospitals'), (3, 'HospitalDoctors'), (4, 'Patients'), (5, 'Labs'), (6, 'Pharmacy'), (0, 'Admin')], max_length=50),
        ),
    ]
