# Generated by Django 3.2.5 on 2021-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210821_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctors',
            name='name_title',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
