# Generated by Django 3.2.5 on 2021-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210815_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_session_id',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
