# Generated by Django 3.2.5 on 2021-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='otp_session_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
