# Generated by Django 3.2.5 on 2021-08-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_hospitaldoctors_name_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldoctors',
            name='ssn_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='user/profile_pic'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Doctor/profile/images'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='hospital/profile'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
    ]
