# Generated by Django 3.2.5 on 2021-09-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_linkdin_pharmacy_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='is_deactive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_deactive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
