# Generated by Django 3.2.5 on 2021-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210821_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='Doctor/profile/images'),
        ),
    ]
