# Generated by Django 3.2.5 on 2021-08-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_hospitaldoctors_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Doctor/profile/images'),
        ),
    ]
