# Generated by Django 3.2.5 on 2021-08-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_hospitaldoctors_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctors',
            name='specialist',
            field=models.CharField(default='', max_length=50),
        ),
    ]
