# Generated by Django 3.2.5 on 2021-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_hospitaldoctors_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='specialist',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
