# Generated by Django 3.2.5 on 2021-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210822_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default='', max_length=500, null=True, upload_to='user/profile_pic'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='Doctor/profile/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='profile_pic',
            field=models.FileField(default='', max_length=500, null=True, upload_to='hospital/profile'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
    ]
