# Generated by Django 3.2.5 on 2021-09-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_patients_add_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='added_by_hospital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
