# Generated by Django 3.2.5 on 2021-09-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('applied_time', models.TimeField()),
                ('is_applied', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('accepted_time', models.DateField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
                ('hospitalstaffdoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalservices')),
            ],
        ),
    ]
