# Generated by Django 3.2.5 on 2021-09-18 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('booking_type', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('applied_date', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('applied_time', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('is_applied', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_taken', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('modified_time', models.TimeField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('add_note', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitalstaffdoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentReliefPetient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.booking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patients')),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_date', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('applied_time', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('is_applied', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_taken', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('modified_time', models.TimeField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('add_note', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSymptons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('level', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Report', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('Description', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('number_of_attempt', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('dose_per_day', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('number_of_days', models.IntegerField(blank=True, default=1, null=True)),
                ('time_to_take', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBottelAndInjections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('BI_content', models.FileField(blank=True, choices=[(1, 'bottle'), (2, 'Injection')], default='', null=True, upload_to='')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[(1, 'Processed'), (2, 'Successed'), (3, 'Failed'), (4, 'Cancelled'), (5, 'Refunded')], default='', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges')),
            ],
        ),
    ]
