# Generated by Django 3.2.5 on 2021-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='applied_date',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='applied_time',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
