# Generated by Django 3.2.5 on 2021-09-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patient', '0002_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.labs'),
            preserve_default=False,
        ),
    ]
