# Generated by Django 3.2.5 on 2021-09-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210926_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='Slot',
            new_name='slot',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Notification',
            new_name='Notification_type',
        ),
    ]
