# Generated by Django 3.2.5 on 2021-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_booking_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accepted_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
