# Generated by Django 3.2.5 on 2021-09-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210926_1653'),
        ('patient', '0003_auto_20210926_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fisrt_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('zip_Code', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('alternate_mobile', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('profile_pic', models.FileField(blank=True, default='', null=True, upload_to='patients/profile/images/%Y/%m/%d/')),
                ('gender', models.CharField(default='', max_length=255, null=True)),
                ('bloodgroup', models.CharField(default='', max_length=255, null=True)),
                ('is_appiled', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('petient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patients')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='for_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.forsome'),
        ),
    ]
