# Generated by Django 3.2.5 on 2021-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210909_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='taken_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
