# Generated by Django 3.2.5 on 2021-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_slot_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='report',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
