# Generated by Django 3.2.5 on 2021-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210919_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='amount',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
