# Generated by Django 3.2.5 on 2021-09-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('accounts', '0002_auto_20210926_1653'),
        ('patient', '0005_slot_send_to_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hospitalstaffdoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalbooking', to='patient.booking'),
        ),
        migrations.CreateModel(
            name='ReBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('applied_date', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('applied_time', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('is_applied', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_taken', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('modified_time', models.TimeField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('add_note', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('next_date', models.DateTimeField(auto_now_add=True)),
                ('previous_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Admited',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bed_charges', models.FloatField(blank=True, default=0, null=True)),
                ('other_charges', models.FloatField(blank=True, default=0, null=True)),
                ('doctor_charges', models.FloatField(blank=True, default=0, null=True)),
                ('tax_charges', models.FloatField(blank=True, default=0, null=True)),
                ('total_charges', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('admined_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('add_note', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.rebooking')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalrooms')),
            ],
        ),
    ]
