# Generated by Django 3.2.5 on 2021-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210913_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
