# Generated by Django 3.2.5 on 2021-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_slot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='booking_for',
            field=models.CharField(blank=True, choices=[(1, 'Hospital'), (2, 'Laboratory'), (3, 'Pharmacy')], default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
