# Generated by Django 3.2.5 on 2021-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20210929_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forsome',
            old_name='alternate_mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='forsome',
            name='dob',
        ),
        migrations.AddField(
            model_name='forsome',
            name='add_notes',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='forsome',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forsome',
            name='email',
            field=models.EmailField(blank=True, default='xyz@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='forsome',
            name='name_title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
