# Generated by Django 3.2.5 on 2021-09-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20210919_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='bookingandlabtest',
        ),
    ]
