# Generated by Django 3.2.5 on 2021-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_booking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_note',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
