# Generated by Django 3.2.5 on 2021-09-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20210930_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forsome',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='forsome',
            name='ID_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='someone/ID/images/%Y/%m/%d/'),
        ),
    ]
