# Generated by Django 3.2.5 on 2021-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_booking_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='modified_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='add_note',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
