# Generated by Django 3.2.5 on 2021-09-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='User',
            new_name='user',
        ),
    ]
