# Generated by Django 3.2.5 on 2021-09-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_forsome_petient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forsome',
            old_name='petient',
            new_name='patient',
        ),
    ]
