# Generated by Django 3.2.5 on 2021-09-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_rename_user_temp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentreliefpetient',
            name='booking',
        ),
    ]
