# Generated by Django 3.2.5 on 2021-09-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_treatmentreliefpetient_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentreliefpetient',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.booking'),
            preserve_default=False,
        ),
    ]
