# Generated by Django 3.2.5 on 2021-09-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_serviceandcharges'),
        ('patient', '0011_booking_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges'),
        ),
    ]
