# Generated by Django 3.2.5 on 2021-10-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitals_firm'),
        ('patient', '0011_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admited',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='followedup',
            options={'ordering': ['next_date']},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientmedicine',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientreports',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='picturesformedicine',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rebooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='treatmentreliefpetient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orders',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_booking_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='taken_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='phoneOPTforoders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('validated', models.BooleanField(blank=True, default=False, null=True)),
                ('otp_session_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.orders')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patients')),
            ],
        ),
    ]
