# Generated by Django 3.2.5 on 2021-09-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_treatmentreliefpetient_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='amount',
        ),
    ]
