# Generated by Django 3.2.5 on 2021-10-05 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0012_auto_20211005_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneoptforoders',
            name='patient',
        ),
        migrations.AddField(
            model_name='phoneoptforoders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
