# Generated by Django 3.2.5 on 2021-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_remove_slot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
