# Generated by Django 3.2.5 on 2021-10-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0013_auto_20211005_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneoptforoders',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.orders'),
        ),
        migrations.AlterField(
            model_name='phoneoptforoders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
