# Generated by Django 3.2.5 on 2021-09-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20210913_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentReliefPetient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('disease', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('treatment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.booking')),
            ],
        ),
    ]
