# Generated by Django 3.2.5 on 2021-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_treatmentreliefpetient'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentreliefpetient',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
