# Generated by Django 3.2.5 on 2021-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20211006_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesformedicine',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
