# Generated by Django 3.2.5 on 2021-09-23 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_patients_is_active'),
        ('patient', '0014_slot_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesForMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription', models.FileField(blank=True, default='', max_length=256, null=True, upload_to=None)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('applied_date', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('applied_time', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('is_applied', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_taken', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('modified_time', models.TimeField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('add_note', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('report', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('desc', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy')),
            ],
        ),
    ]
