# Generated by Django 3.2.5 on 2021-09-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patient', '0015_treatmentreliefpetient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentreliefpetient',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='treatmentreliefpetient',
            name='treatment',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='treatmentreliefpetient',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentreliefpetient',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.patients'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PatientSymptons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('level', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Report', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('Description', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('number_of_attempt', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('dose_per_day', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('number_of_days', models.IntegerField(blank=True, default=1, null=True)),
                ('time_to_take', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBottelAndInjections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('BI_content', models.FileField(blank=True, choices=[(1, 'bottle'), (2, 'Injection')], default='', null=True, upload_to='')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TreatmentReliefPetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
        ),
    ]
