# Generated by Django 3.2.5 on 2021-10-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospitalstaffdoctorschedual_opd_duration'),
        ('accounts', '0007_customuser_otp'),
        ('patient', '0015_picturesformedicine_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='patients/documents/fiel/%Y/%m/%d/')),
                ('file_date', models.DateField(blank=True, null=True)),
                ('file_time', models.TimeField(blank=True, null=True)),
                ('file_purpose', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('file_addnote', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitaldoctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patients')),
                ('treatmentreliefpetient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatmentreliefpetient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
