# Generated by Django 3.2.5 on 2021-10-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfile',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.booking'),
            preserve_default=False,
        ),
    ]
