# Generated by Django 3.2.5 on 2021-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_remove_picturesformedicine_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesformedicine',
            name='store_invoice',
            field=models.FileField(blank=True, default='', max_length=256, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
