# Generated by Django 3.2.5 on 2021-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20210915_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.FloatField(default=250),
            preserve_default=False,
        ),
    ]
