# Generated by Django 3.2.5 on 2021-09-18 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_serviceandcharges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0017_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[(1, 'Successed'), (2, 'Failed'), (3, 'Cancelled'), (4, 'Refunded')], default='', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges')),
            ],
        ),
    ]
