# Generated by Django 3.2.5 on 2021-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_auto_20210923_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturesformedicine',
            name='applied_date',
            field=models.DateField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='picturesformedicine',
            name='applied_time',
            field=models.TimeField(blank=True, max_length=64, null=True),
        ),
    ]
