# Generated by Django 3.2.5 on 2021-10-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospitalstaffdoctorschedual_opd_duration'),
        ('accounts', '0007_customuser_otp'),
        ('patient', '0017_patientfile_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfile',
            name='file_date',
        ),
        migrations.RemoveField(
            model_name='patientfile',
            name='file_time',
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.booking'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='hospitaldoctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patients'),
        ),
    ]
