# Generated by Django 3.2.5 on 2021-09-18 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_serviceandcharges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0018_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='Orders',
        ),
    ]
