# Generated by Django 3.2.5 on 2021-10-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospitalstaffdoctorschedual_opd_duration'),
        ('patient', '0018_auto_20211012_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, default='OPD', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges'),
        ),
    ]
