# Generated by Django 3.2.5 on 2021-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hospitalstaffdoctor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Processed'), (2, 'Successed'), (3, 'Failed'), (4, 'Cancelled'), (5, 'Refunded')], default='', max_length=64, null=True),
        ),
    ]
