# Generated by Django 3.2.5 on 2021-10-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_customuser_otp'),
        ('patient', '0019_auto_20211012_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='for_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.forsome'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.labs'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
