# Generated by Django 3.2.5 on 2021-10-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20211013_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
