# Generated by Django 3.2.5 on 2021-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20210918_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_for',
            field=models.CharField(blank=True, choices=[(1, 'Hospital'), (2, 'Lab'), (3, 'Pharmacy')], default='', max_length=64, null=True),
        ),
    ]
