# Generated by Django 3.2.5 on 2021-10-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_auto_20211025_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labtest', to='patient.slot'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('Processed', 'Processed'), ('Successed', 'Successed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='', max_length=64, null=True),
        ),
    ]
