# Generated by Django 3.2.5 on 2021-11-11 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_auto_20211025_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_within_5',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
