# Generated by Django 3.2.5 on 2021-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='opd_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
