# Generated by Django 3.2.5 on 2021-08-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hospitalphone'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_head', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('department_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='hospitalServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('service_rate', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments')),
            ],
        ),
        migrations.DeleteModel(
            name='Mobiles',
        ),
        migrations.AddField(
            model_name='departmentphone',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.departments'),
        ),
        migrations.AddField(
            model_name='departmentphone',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals'),
        ),
    ]
