# Generated by Django 3.2.5 on 2021-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospitalstaffdoctors_opd_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='emegency_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='home_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='online_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
