# Generated by Django 3.2.5 on 2021-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210817_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='hospitalstaffs',
            name='ssn_id',
            field=models.IntegerField(default=1),
        ),
    ]
