# Generated by Django 3.2.5 on 2021-08-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210814_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='email',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
