# Generated by Django 3.2.5 on 2021-09-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210929_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalstaffdoctors',
            old_name='emegency_charges',
            new_name='emergency_charges',
        ),
        migrations.RemoveField(
            model_name='hospitalstaffdoctors',
            name='online_charges',
        ),
    ]
