# Generated by Django 3.2.5 on 2021-08-14 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210814_1053'),
        ('hospital', '0003_auto_20210814_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalTreatments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('treatment_rate', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaldoctors')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
        migrations.RenameModel(
            old_name='DepartmentPhone',
            new_name='DepartmentPhones',
        ),
        migrations.RenameModel(
            old_name='hospitalMedia',
            new_name='HospitalMedias',
        ),
        migrations.DeleteModel(
            name='hospitalServices',
        ),
    ]
