# Generated by Django 3.2.5 on 2021-08-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210814_1206'),
        ('hospital', '0004_auto_20210814_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('insurance_name', models.CharField(blank=True, choices=[(1, 'CashLess'), (2, 'No Cahsless')], default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
    ]
