# Generated by Django 3.2.5 on 2021-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210819_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrooms',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospitalrooms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
