# Generated by Django 3.2.5 on 2021-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210929_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalstaffdoctorschedual',
            name='shift',
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='break_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='break_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
