# Generated by Django 3.2.5 on 2021-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210929_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='opd_duration',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
