# Generated by Django 3.2.5 on 2021-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210819_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrooms',
            name='room_no',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
    ]
