# Generated by Django 3.2.5 on 2021-08-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_name_title'),
        ('hospital', '0005_insurances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurances',
            name='is_default',
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_title', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
    ]
