# Generated by Django 3.2.5 on 2021-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hospitalrooms_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrooms',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
