# Generated by Django 3.2.5 on 2021-10-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_user_type'),
        ('hospital', '0006_hospitalstaffdoctorschedual_opd_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalstaffdoctors', to='accounts.hospitals'),
        ),
    ]
