# Generated by Django 3.2.5 on 2021-10-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_user_type'),
        ('hospital', '0007_alter_hospitalstaffdoctors_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaldoctor', to='accounts.hospitaldoctors'),
        ),
    ]
