# Generated by Django 3.2.5 on 2021-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospitalrooms_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalrooms',
            old_name='room_type',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='hospitalrooms',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalrooms',
            name='occupied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
