# Generated by Django 3.2.5 on 2021-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_hospitalstaffdoctors_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='is_homevisit_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
