# Generated by Django 3.2.5 on 2021-08-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitaldoctors_ssn_id'),
        ('hospital', '0008_auto_20210819_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaffDoctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joindate', models.DateField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaldoctors')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
    ]
