# Generated by Django 3.2.5 on 2021-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospitalstaffdoctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='ssn_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
