# Generated by Django 3.2.5 on 2021-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_hospitalstaffdoctors_ssn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
