# Generated by Django 3.2.5 on 2021-08-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_hospitalstaffdoctors_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalstaffdoctors',
            name='email',
        ),
    ]
