# Generated by Django 3.2.5 on 2021-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_hospitalstaffdoctors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
