# Generated by Django 3.2.5 on 2021-08-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20210821_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='hospital_staff',
        ),
        migrations.AddField(
            model_name='departments',
            name='hospital_staff_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors'),
            preserve_default=False,
        ),
    ]
