# Generated by Django 3.2.5 on 2021-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20210822_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctors',
            name='is_virtual_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
