# Generated by Django 3.2.5 on 2021-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_hospitalstaffdoctorschedual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalstaffdoctorschedual',
            name='shift',
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='work',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='days',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=50, null=True),
        ),
    ]
