# Generated by Django 3.2.5 on 2021-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20210822_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalstaffdoctorschedual',
            name='days',
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='day',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening'), ('All-Day', 'All-Day')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
