# Generated by Django 3.2.5 on 2021-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20210824_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
