# Generated by Django 3.2.5 on 2021-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20210824_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalstaffdoctorschedual',
            old_name='day',
            new_name='friday',
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='monday',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='saturday',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='sunday',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='thursday',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='tueday',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffdoctorschedual',
            name='wednesday',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='shift',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=50, null=True),
        ),
    ]
