# Generated by Django 3.2.5 on 2021-08-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20210825_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalstaffdoctorschedual',
            old_name='tueday',
            new_name='tuesday',
        ),
    ]
