# Generated by Django 3.2.5 on 2021-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_rename_tueday_hospitalstaffdoctorschedual_tuesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctorschedual',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening'), ('All-Day', 'All-Day')], default='', max_length=50, null=True),
        ),
    ]
