# Generated by Django 3.2.5 on 2021-09-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_hospitalstaffdoctorschedual_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmedias',
            name='Media_desc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
