# Generated by Django 3.2.5 on 2021-09-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_hospitalmedias_media_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalmedias',
            old_name='Media_desc',
            new_name='media_desc',
        ),
    ]
