# Generated by Django 3.2.5 on 2021-09-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_patients_added_by_hospital'),
        ('hospital', '0027_hospitalspatients_name_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalspatients',
            name='hospital',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.hospitals'),
            preserve_default=False,
        ),
    ]
