# Generated by Django 3.2.5 on 2021-09-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_hospitalspatients_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalspatients',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
