# Generated by Django 3.2.5 on 2021-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_hospitalspatients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalspatients',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospitalspatients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
