# Generated by Django 3.2.5 on 2021-09-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_patients_added_by_hospital'),
        ('hospital', '0030_auto_20210905_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('service_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
    ]
